### ISSUE TITLE
Submission Package

### ISSUE THREAD

**Issue by McRawly** [hackforla/ems-triage-tracker#7]
### Overview
Provide collateral for the Submission Package

Download "Submission Package.docx" from this Google Drive and update on your local computer.
Google Docs destroys the formatting.
https://drive.google.com/drive/folders/1LKqeoTUwWKF7_p4FVS-H7cCN1ru-jVLk

### Action Items
- [ ]  Page 1/7: Individual Participant or Team Representative Contact Information
  - [ ]  First Name
  - [ ]  Last Name
  - [ ]  email
- [ ]  Page 2/7: Legal Participant
  - [x]  All participants 18+ YES/NO
  - [ ]  Contact Information for ONE US CITIZEN
    - [ ]  Same as above
- [ ]  Page 3/7: Team Members Info (by default we'll use EMS roster answers)
  - [ ]  First Name *
  - [ ]  Last Name *
  - [ ]  email *
  - [ ]  Experience, strengths and commitment *
- [x]  Page 4/7: 
  - [x]  Acknowledge you can only submit once. *
  - [x]  Choose contest: 010. *
- [ ]  Page 5/7: 
  - [ ]  What is the title of this submission? (multi-line input) *
  - [ ]  Please provide a high level summary of your submission. (250 chars) *
  - [ ]  Please include details of the specific areas of the contest’s requirements that you have addressed and the approach you have taken to complete your submission. (500 chars) *
  - [ ]  What stage of development is this solution or prototype in? (50 chars) *
  - [ ]  If you had $15,000 to continue refining this submission, what would be your next steps? (150 chars) *
- [ ]  Page 6/7: Technology and Visual Assets
  - [ ]  6.1 Please tell us about your submission’s platform and hardware Have you tested your application on the recommended emulator? (>1000 chars) * (Recommended emulators (Android Studio: https://developer.android.com/studio/ or iOS: Test Flight: https://developer.apple.com/testflight/)
  - [ ]  6.2 Does the application need to be installed on a mobile device or tablet to demonstrate the functionality? * checkboxes: mobile, tablet, N/A, other.
  - [ ]  6.3 Select the platform for your application * modal radio boxes: iOS, Android, web application.
  - [ ]  6.4 If your application utilizes a backend for any data or services, is it... (not *) modal radio boxes: self contained, cloud services, virtual machine.  (See NIST recommendations for each configuration. Please note all applications must operate on iOS 12 or newer, Android 9 or newer)
  - [ ]  6.5 Upload file button. (Contestant must provide instructions on how to import/how to setup application, server, container, etc. To enable NIST to install you application on a lab top or mobile device – please provide an installation walk through guide (one attachment in presentation format) 1. Installation Walk Through Video (less than 5 minutes) 2. Screen Shots of key set up decision points 3. All Emulator Settings 4. Provide any administrative credentials 5. If your submission utilizes a virtual machine or container - include IP address, administrative user/password, any other useful information for your virtual machine or docker container.) *
  - [ ] 6.6 What technology is your submission developed with? Please list the programming languages, APIs, SDKs, etc.* (unlimited chars)
  - [ ] 6.7 Deliverable # 1 "Upload button" 
    - [ ]  Please describe the file that you are submitting. * (250 chars)
  - [ ] 6.8 Deliverable # 2 "Upload button" 
    - [ ]  Please describe the file that you are submitting. * (250 chars)
  - [ ] 6.9 Deliverable # 3 "Upload button" 
    - [ ]  Please describe the file that you are submitting. * (250 chars)
  - [ ] 6.10 If your submission is on Github or a similar platforms, please include the URL below. (not *) single-line input
- [x]  Page 7/7: Submission Checklist
  - [x] I have read and understand the Official Rules, Terms and Conditions, and fully agree to them. *
  - [x] I am an individual and/or represent a team, or I represent a private entity that meets all eligibility criteria as stated in the Official Rules, Terms and Conditions. *
  - [x] I participated in this challenge ethically and in the spirit of fair competition, I did not receive any assistance from the judges, and I utilized information and materials provided by the challenge administration website appropriately when preparing this submission. *
  - [x] I understand that the Redflash and SecondMuse website is hosted by a private entity and is not a service of NIST. The solicitation and collection of personal or individually identifiable information is subject to the host’s privacy and security policies. Personal or individually identifiable information collected on this website will be shared with NIST for prize payment purposes only, and only for winners of the Challenge. *
  - [x] I acknowledge that I have read the Redflash and SecondMuse’s data privacy, use, security, and retention policies and understand that all data, except that expressly marked for government use, is subject to these Redflash and SecondMuse policies. I further agree not to hold NIST or the U.S. Government liable for the protection, use, or retention of any information submitted through this website. *

### Resources/Instructions
Submit URLs:
[Submit Page] https://www.techtoprotectchallenge.org/participate-online/
[Actual Form] https://tech-to-protect-challenge-2.forms.fm/tech-to-protect-challenge-online-contest/forms/6544

All screenshots from the submission process are here: 
https://drive.google.com/drive/folders/1LKqeoTUwWKF7_p4FVS-H7cCN1ru-jVLk

**Comment by lwanderson-triage** [comment]
Reviewing with Bonnie on Thursday, November 14.

**Comment by lwanderson-triage** [comment]
Draft document emailed to Bonnie on Thursday, November 14.
